// Generated by CoffeeScript 1.6.3
(function() {
  define(function(require) {
    var $, foo;
    $ = require('jquery');
    foo = {};
    foo.bar = function() {
      return alert('Hello world!');
    };
    return foo;
  });

}).call(this);
