// Generated by CoffeeScript 1.6.3
(function() {
  var $, foo;

  $ = require('jquery');

  foo = {};

  foo.bar = function() {
    var data, tpl;
    tpl = require('./main.tpl.html');
    data = [
      {
        name: 'foo'
      }, {
        name: 'bar'
      }
    ];
    return $('#foo-div').html(tpl.render(data));
  };

  module.exports = foo;

}).call(this);
